# Generated by Django 2.2.7 on 2019-11-29 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='approaches',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='chasing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='climbing',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='eating',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='foraging',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='indifferent',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='kuks',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='moans',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='quaas',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='running',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='runs_from',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='shift',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_flags',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='tail_twiches',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='unique_squirrel_id',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
