# Generated by Django 2.2.7 on 2019-11-30 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20191129_2151'),
    ]

    operations = [
        migrations.RenameField(
            model_name='squirrel',
            old_name='tail_twiches',
            new_name='tail_twitches',
        ),
    ]
